version: "3.8"
services:
  antminer_to_mqtt:
    build: .
    container_name: antminer_to_mqtt
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/antminer_to_mqtt/app:/usr/src/app
    restart: unless-stopped
